### ISSUE TITLE
[Question] Anyone attempted to use this plugin for VOD MP4 files? 

### ISSUE THREAD

**Issue by xSignificant** [bcc-code/videojs-hls-live-sync#11]
Did anyone attempt to use this plugin for VOD MP4 files? Is it even possible?

**Comment by KillerX** [comment]
Hey, I have not tried and I am not sure if it would work in the shape it is in now. I implemented this specifically for live stream as that was the problem I was trying to solve. 

I suspect that it should be simpler to achieve on a VOD as there you are able to transmit and jump to an absolute time value, compared to live where you can not really seek to an absolute point in the stream. TBH If I was writing a new plugin for VOD I would just sync the play command, maybe something like submit a start at wall clock now +0.5 seconds m, and then adjust for potential drift.

I will close the issue since I feel that the question is answered, but feel free to comment and tag me if you have more questions.
